;              
CREATE USER IF NOT EXISTS "SA" SALT '84f733ce871fdf91' HASH '5a1aa213baf5a8ba4ba4e13d0531f836f30d89a9148e735c7af301caf2831b7f' ADMIN;          
CREATE SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_5856C1FD_C1C5_4730_8DAA_C29149A3322B" START WITH 1 BELONGS_TO_TABLE; 
CREATE SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_AE34E076_E1F1_4382_9F7B_98DD40943010" START WITH 1 BELONGS_TO_TABLE; 
CREATE SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_77385701_BE8E_4363_80D7_CE912E7A2CC0" START WITH 1 BELONGS_TO_TABLE; 
CREATE SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_DF16A1E2_BEC5_42A8_91D2_FC528AB222CB" START WITH 1 BELONGS_TO_TABLE; 
CREATE SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_D4A66E9A_DBF6_4628_AABF_BEABCA0FB6A1" START WITH 1 BELONGS_TO_TABLE; 
CREATE MEMORY TABLE "PUBLIC"."EMPRUNT"(
    "ID" INTEGER DEFAULT NEXT VALUE FOR "PUBLIC"."SYSTEM_SEQUENCE_77385701_BE8E_4363_80D7_CE912E7A2CC0" NOT NULL NULL_TO_DEFAULT SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_77385701_BE8E_4363_80D7_CE912E7A2CC0",
    "DATE_DEBUT" TIMESTAMP,
    "DATE_FIN" TIMESTAMP,
    "EXEMPLAIREID" INTEGER,
    "MEMBREID" INTEGER,
    "PROLONGATION" BOOLEAN,
    "RELANCE" BOOLEAN,
    "TERMINE" BOOLEAN
);       
ALTER TABLE "PUBLIC"."EMPRUNT" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_C" PRIMARY KEY("ID");       
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.EMPRUNT;  
CREATE MEMORY TABLE "PUBLIC"."EXEMPLAIRE"(
    "ID" INTEGER DEFAULT NEXT VALUE FOR "PUBLIC"."SYSTEM_SEQUENCE_D4A66E9A_DBF6_4628_AABF_BEABCA0FB6A1" NOT NULL NULL_TO_DEFAULT SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_D4A66E9A_DBF6_4628_AABF_BEABCA0FB6A1",
    "DISPONIBILITE" BOOLEAN,
    "LIVREID" INTEGER
);    
ALTER TABLE "PUBLIC"."EXEMPLAIRE" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_4" PRIMARY KEY("ID");    
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.EXEMPLAIRE;               
CREATE MEMORY TABLE "PUBLIC"."LIVRE"(
    "ID" INTEGER DEFAULT NEXT VALUE FOR "PUBLIC"."SYSTEM_SEQUENCE_AE34E076_E1F1_4382_9F7B_98DD40943010" NOT NULL NULL_TO_DEFAULT SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_AE34E076_E1F1_4382_9F7B_98DD40943010",
    "AUTEUR" VARCHAR(50),
    "DATE_PUBLICATION" TIMESTAMP,
    "GENRE" VARCHAR(25),
    "RESUME" VARCHAR(2500),
    "TITRE" VARCHAR(50),
    "URL_PHOTO" VARCHAR(500)
);     
ALTER TABLE "PUBLIC"."LIVRE" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_45" PRIMARY KEY("ID");        
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.LIVRE;    
CREATE MEMORY TABLE "PUBLIC"."MEMBRE"(
    "ID" INTEGER DEFAULT NEXT VALUE FOR "PUBLIC"."SYSTEM_SEQUENCE_DF16A1E2_BEC5_42A8_91D2_FC528AB222CB" NOT NULL NULL_TO_DEFAULT SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_DF16A1E2_BEC5_42A8_91D2_FC528AB222CB",
    "ADRESSE" VARCHAR(255),
    "ADRESSE_MAIL" VARCHAR(50),
    "CODE_POSTAL" VARCHAR(255),
    "MOT_DE_PASSE" VARCHAR(10),
    "NOM" VARCHAR(50),
    "PRENOM" VARCHAR(50),
    "TELEPHONE" VARCHAR(255),
    "VILLE" VARCHAR(50)
);        
ALTER TABLE "PUBLIC"."MEMBRE" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_8" PRIMARY KEY("ID");        
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.MEMBRE;   
CREATE MEMORY TABLE "PUBLIC"."RESERVATION"(
    "ID" INTEGER DEFAULT NEXT VALUE FOR "PUBLIC"."SYSTEM_SEQUENCE_5856C1FD_C1C5_4730_8DAA_C29149A3322B" NOT NULL NULL_TO_DEFAULT SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_5856C1FD_C1C5_4730_8DAA_C29149A3322B",
    "DATE_DISPO" TIMESTAMP,
    "LIVREID" INTEGER,
    "MEMBREID" INTEGER,
    "NUM_POSITION_RESA" INTEGER,
    "STATUT" VARCHAR(255)
);
ALTER TABLE "PUBLIC"."RESERVATION" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_2" PRIMARY KEY("ID");   
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.RESERVATION;              
ALTER TABLE "PUBLIC"."RESERVATION" ADD CONSTRAINT "PUBLIC"."FK1S2U93O0NDGNXYKDCSV3HL5HH" FOREIGN KEY("LIVREID") REFERENCES "PUBLIC"."LIVRE"("ID") NOCHECK;     
ALTER TABLE "PUBLIC"."EXEMPLAIRE" ADD CONSTRAINT "PUBLIC"."FKJM4TAH0RKI9L0C7972Y1TQXVC" FOREIGN KEY("LIVREID") REFERENCES "PUBLIC"."LIVRE"("ID") NOCHECK;      
ALTER TABLE "PUBLIC"."EMPRUNT" ADD CONSTRAINT "PUBLIC"."FK9BJWBTY3C4QBO4BK6UIHCW7XK" FOREIGN KEY("EXEMPLAIREID") REFERENCES "PUBLIC"."EXEMPLAIRE"("ID") NOCHECK;               
ALTER TABLE "PUBLIC"."EMPRUNT" ADD CONSTRAINT "PUBLIC"."FKLVU72MWQ4O0CEXB42AH1MT1OA" FOREIGN KEY("MEMBREID") REFERENCES "PUBLIC"."MEMBRE"("ID") NOCHECK;       
ALTER TABLE "PUBLIC"."RESERVATION" ADD CONSTRAINT "PUBLIC"."FKNMAALPXQM9INP3X32H0OYTO58" FOREIGN KEY("MEMBREID") REFERENCES "PUBLIC"."MEMBRE"("ID") NOCHECK;   
